name: Test Workflow

on:
  push:
    branches: 
      - main

jobs:
  thing:
    name: Do thing
    runs-on: ubuntu-latest
    steps:
      - name: Do thing 1
        run: exit 1
  
  repsonse:
    name: Respond to failure
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.conclusion == 'timed_out'
    steps:
      - name: Do thing 2
        run: echo hi